# Generated by Django 2.0.6 on 2018-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('bank', '0005_auto_20180615_1603'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learned_entries',
            field=models.ManyToManyField(related_name='users', through='study.WordRecord', to='bank.Entry'),
        ),
    ]
