# Generated by Django 2.0.6 on 2018-06-21 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0005_auto_20180615_1603'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordRecord',
            new_name='EntryRecord',
        ),
    ]
