# Generated by Django 2.0.6 on 2018-06-27 02:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20180627_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrecord',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, size=None),
        ),
    ]
