# Generated by Django 2.0.6 on 2018-06-21 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20180621_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryrecord',
            name='wait',
        ),
        migrations.AddField(
            model_name='entryrecord',
            name='next_review_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
