# Generated by Django 2.0.6 on 2018-06-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20180621_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrecord',
            name='next_review_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
