# Generated by Django 2.0.6 on 2018-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20180626_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
