# Generated by Django 2.0.6 on 2018-06-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_entryrecord_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entryrecord',
            name='next_review_date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entryrecord',
            name='proficiency',
            field=models.SmallIntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='entryrecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
