# Generated by Django 2.0.6 on 2018-06-26 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20180626_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrecord',
            name='starred_sentence_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
