# Generated by Django 2.0.6 on 2018-06-26 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_entryrecord_starred_sentence_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrecord',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
            preserve_default=False,
        ),
    ]
