# Generated by Django 2.0.6 on 2018-06-14 01:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=30)),
                ('level', models.SmallIntegerField()),
                ('definitions', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('definition_rates', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('phonetic', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('sentencesTemp', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new repo', max_length=50)),
                ('words', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('amount', models.IntegerField(default=0)),
                ('entries', models.ManyToManyField(related_name='repos', to='bank.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.TextField()),
                ('chinese', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='bank.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='bank.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
