# Generated by Django 2.0.6 on 2018-06-14 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='bank.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_stars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='star',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='star',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='sentencesTemp',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='words',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
