# Generated by Django 2.0.6 on 2018-06-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180614_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='phonetic',
            new_name='pronounce',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='definition_rates',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='level',
        ),
        migrations.AddField(
            model_name='entry',
            name='rank',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='reference',
            field=models.TextField(default=''),
        ),
    ]
