# Generated by Django 2.0.6 on 2018-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180614_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rank',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
