# Generated by Django 2.0.6 on 2018-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20180614_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='word',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(db_index=True, default='new repo', max_length=50, unique=True),
        ),
    ]
