# Generated by Django 2.0.6 on 2018-06-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20180615_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AlterField(
            model_name='entry',
            name='word',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
