# Generated by Django 2.0.6 on 2018-06-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20180621_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentencestar',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='sentencestar',
            name='user',
        ),
        migrations.DeleteModel(
            name='SentenceStar',
        ),
    ]
