# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('level', models.SmallIntegerField()),
                ('definitions', models.CharField(default='[]', max_length=800)),
                ('phonetic', models.CharField(default='{}', max_length=1000)),
                ('examples', models.CharField(default='[]', max_length=3000)),
            ],
        ),
    ]
