# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='examples',
            new_name='sentences',
        ),
    ]
