# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170209_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('words', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='definitions',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='phonetic',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sentences',
            field=models.TextField(default='[]'),
        ),
    ]
