# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170209_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(default='new repo', max_length=50),
        ),
        migrations.AlterField(
            model_name='repo',
            name='words',
            field=models.TextField(default=[]),
        ),
    ]
