# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(default={})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
