# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170219_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='phrases',
        ),
    ]
