# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_entry_phrases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='definition_rates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='entry',
            name='definitions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='phonetic',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sentences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
