# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170813_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='entries',
            field=models.ManyToManyField(related_name='repos', to='app.Entry'),
        ),
    ]
