# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_repo_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='sentences',
            new_name='sentencesTemp',
        ),
        migrations.AddField(
            model_name='sentence',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='app.Entry'),
            preserve_default=False,
        ),
    ]
