# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170813_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='text',
            new_name='english',
        ),
    ]
