# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170827_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='chinese',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
