# Generated by Django 2.0.6 on 2018-06-13 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sentence_chinese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
